### ISSUE TITLE
cannot use ne peut pas utiliser

### ISSUE THREAD

**Issue by xti122** [FinalException/AntiSigma#1]
how do you use that, i tried to run like jar but it still does not work
can you do a video tutorial

comment utilisez-vous cela, j'ai essayé de courir comme jar mais ça ne marche toujours pas
pouvez-vous faire un tutoriel vidéo

**Comment by xti122** [comment]
can you help 
pouvez-vous aider

**Comment by xti122** [comment]
hello

**Comment by NotVerble** [comment]
Please provide a stacktrace of the error.

**Comment by xti122** [comment]
how to run java file

**Comment by xti122** [comment]
help you have jar file

**Comment by FinalException** [comment]
there isn't a runnable file currently, you need to compile it yourself. Check the readme
