### ISSUE TITLE
doesn't.. really work?

### ISSUE THREAD

**Issue by DogGuy68** [FinalException/AntiSigma#2]
hello, after decrypt it's still very encrypted and can't really see much of the shitty code
https://user-images.githubusercontent.com/48660141/54499426-40ffe400-491a-11e9-8e29-ee7230565498.png

**Comment by FinalException** [comment]
this is meant to decrypt the bytecode obfuscation, not rename classes. use a class name normalizer from the java-deobfuscator github

**Comment by DogGuy68** [comment]
could you please give me more details? i still can't figure it out, it's still very obfuscated, i have no idea what i'm doing wrong

**Comment by FinalException** [comment]
Sigma has bytecode encryption, string encryption and name obfuscation. This only decrypts the bytecode encryption, it doesn't rename classes or decrypt strings.
